spring.application.name=campussync
# conexion a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/campussync_db
spring.datasource.username=postgres
spring.datasource.password=2127

# para que Spring cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
#para que se imprima todo el código SQL que estés ejecutando por detrás
